# Generated by Django 4.2.6 on 2024-02-01 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('publishedDate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('membershipDate', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField()),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
                ('UserID', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPages', models.IntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=50)),
                ('Book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
            ],
        ),
    ]
