# Generated by Django 4.2.6 on 2024-02-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='BookID',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='user.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='ReturnDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
