# Generated by Django 4.2.6 on 2024-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_borrowedbooks_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='ReturnDate',
            field=models.DateField(),
        ),
    ]
