# Generated by Django 4.2.6 on 2024-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_borrowedbooks_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='ReturnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
