# Generated by Django 4.2.6 on 2024-02-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_borrowedbooks_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book'),
        ),
    ]
