# Generated by Django 4.2.6 on 2024-02-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_borrowedbooks_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
