# Generated by Django 4.2.6 on 2024-02-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_borrowedbooks_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='BookID',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='user.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbooks',
            name='UserID',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
